### PR TITLE
Modify weight, agent and Makefile.

### PR DESCRIPTION
**Pull request by elit8888**

### CODE REVIEW

**Comment by EelaiWind** [comment]
### Some suggestions
* `Matrix Agent::predict` and `Matrix Agent::evaluate_action` are identical functions. Just keep one.
* Should `Matrix Agent::relu(Matrix matrix)` be  a ***static constant*** function? Like this `static Matrix Agent::relu(const Matrix &matrix) const {...}`
* Should we move the implementation of `void AbstractAgent::save_agent()` and `void AbstractAgent::load_agent()` from header file to source file? Header files should only contain short functions.
* Should `inline Matrix operator[] (const int x) const {...}`  return a constant reference instead. Like this `inline const Matrix& operator[] (const int x) const {...} `
* Should we provide an example of `config.txt` and do not modify it? Otherwise, the git tracking is meaningless. The setting of each experiment should be recorded in some otherwhere.

@C14016112 , @elit8888 please take a look and leave your comments. We can merge the pull request if we reach an agreement on them.

**Comment by elit8888** [comment]
1. The original function is `Matrix Agent::predict`, but the abstract rule uses `Matrix Agent::evaluate_action`, so other files calling `predict` function need to be modified if we use the later one.
2. For now I think the `ReLu` function can be extracted to other files, which might contains other activation functions.
3. But I have no clue where to put, another file called `abstract_agent.cpp`?
4. Okay, I did not notice that.
5. Okay.

One other thing, `agent.h, agent.cpp` might need to be renamed, like `dnn-agent` or others, any suggestion?

**Comment by byshiue** [comment]
1. I think that using Matrix Agent::evaluate_action to replace predict is better.
2. Currently, we don't need to consider other activation function. And ReLU is only used in neural network, so I think we do not need to use static.
3. put  in abstract_agent.cpp is ok.
4, 5 no problems.
rename agent to dnn_agent is okay

**Comment by EelaiWind** [comment]
1. Keep `Agent::evaluate_action` and remove another one.
2. Temporarily keep `relu()` in `agent.cpp` because activation functions belong to DNN agent.
3. There is no other functions need to be implemented in `abstract_agent.cpp`, so we keep `save_agent() ` and `load_agent()` in header file for simplicity.
4. Change to `inline const Matrix& operator[] (const int x) const {...}`
5. Rename `config.txt` to `config_example.txt` and only modify it when the format changes.
6. Rename `agent.h, agent.cpp` to `dnn_agent.h, dnn_agent.cpp`. Remember to change the **class name** accordingly.

@elit8888  please help to modify these and submit a new commit. Afterward, @C14016112 please check and accept the pull request. I will add my part after this merge.
Thanks, guys.

**Comment by elit8888** [comment]
Updated.

For now `evolution_strategy` still uses `DnnAgent`. If we want to use `AbstractAgent` it needs dynamic allocation (which might be slower?), or use template.
Maybe there's feature I didn't know, other suggestion?

**Pull request merged**
